---
- name: Install fedmsg packages packages
  yum:
    name:
      - python3-fedmsg
    state: present
    update_cache: true
    enablerepo: "{{ mbs_custom_repo_name }}"
    disable_gpg_check: "{{ mbs_custom_repo_gpg_check }}"
  become: true

- name: Python3 workaround
  pip:
    name:
      - pygments
    executable: /usr/bin/pip3.6
  become: true

- name: Ensure group "fedmsg" exists
  group:
    name: fedmsg
    state: present
  become: true

- name: Ensure user "fedmsg" exists
  user:
    name: fedmsg
    comment: fedmsg
    group: fedmsg
  become: true

- name: Ensure /etc/fedmsg.d/ folder exists
  file:
    path: /etc/fedmsg.d/
    state: directory
    owner: root
    group: fedmsg
    mode: 0755
  become: true

- name: setup basic /etc/fedmsg.d/ contents for internal hosts
  template:
    src: "fedmsg/base/{{ item }}.j2"
    dest: "/etc/fedmsg.d/{{ item }}"
    owner: root
    group: fedmsg
    mode: 0644
  with_items:
    - ssl.py
    - endpoints.py
    - endpoints-mbs-backend.py
    - relay.py
    - logging.py
    - base.py
  become: true
  notify:
    - Reload apache
    - Restart fedmsg-hub
  
- name: Enable the websocket server if we should
  template:
    src: fedmsg/websockets.py.j2
    dest: /etc/fedmsg.d/websockets.py
  when: fedmsg_enable_websocket_server
  become: true
  notify:
    - Restart fedmsg-hub
  
- name: Disable the websocket server if we should..
  file:
    path: /etc/fedmsg.d/websockets.py
    state: absent
  when: not fedmsg_enable_websocket_server
  notify:
    - Restart fedmsg-hub

- name: Set fedmsg ownership on /var/run/fedmsg
  file:
    dest: /var/run/fedmsg/
    mode: 2775
    owner: fedmsg
    group: fedmsg
    state: directory
  become: true

- name: Check if /var/run/fedmsg/monitoring-fedmsg-hub.socket file exists
  stat:
    path: /var/run/fedmsg/monitoring-fedmsg-hub.socket
  become: true
  register: output
  
- name: Create systemd config directory
  file:
    path: /etc/systemd/system/fedmsg-hub.service.d
    state: directory
  become: true
  notify:
    - Reload systemd

- name: Install systemd config file
  template:
    src: fedmsg/fedmsg-hub-systemd.conf.j2
    dest: /etc/systemd/system/fedmsg-hub.service.d/systemd.conf
  become: true
  notify:
    - Reload systemd
    - Restart fedmsg-hub

- name: Create fedmsg-hub systemd file
  template:
    src: fedmsg/fedmsg-hub.service.j2
    dest: /usr/lib/systemd/system/fedmsg-hub.service
  become: true

- name: Fedmsg-hub service
  systemd:
    name: fedmsg-hub
    state: started
    enabled: yes
    daemon_reload: yes
  become: true
