---
- name: Importing specific distro variables
  include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_distribution }}-{{ ansible_distribution_major_version }}.yml"
    - "{{ ansible_distribution }}.yml"
  tags:
    - vars

# base system setup
- include_tasks: system.yml
# rabbitmq
- include_tasks: rabbitmq.yml
  when: mbs_rabbitmq_local | bool
# msb-backend setup
- include_tasks: mbs-backend.yml
  when: mbs_backend | bool
# msb-frontend setup
- include_tasks: mbs-frontend.yml
  when: mbs_frontend | bool
  tags:
    - pki
    - tls
    - certs
