- name: Install RabbitMQ server packages
  yum:
    name:
      - SDL2
      - erlang
      - rabbitmq-server

- name: Apply rabbitmq config
  template:
    src: rabbitmq/rabbitmq.conf.j2
    dest: /etc/rabbitmq/rabbitmq.conf
  notify:
    - Restart RabbitMQ

- name: Start RabbitMQ
  service:
    name: rabbitmq-server
    state: started
    enabled: true

- name: Ensure vhost exists
  rabbitmq_vhost:
    name: "{{ mbs_rabbitmq_vhost }}"
    state: present

- name: Ensure user exists and has access to vhost
  rabbitmq_user:
    user: "{{ mbs_rabbitmq_username }}"
    password: "{{ mbs_rabbitmq_password }}"
    vhost: "{{ mbs_rabbitmq_vhost }}"
    configure_priv: .*
    read_priv: .*
    write_priv: .*
    state: present
