# Default task file for mbs role

- name: Ensuring we have fedmsg
  include_role:
    name: fedmsg

- name: Add the buildtools repo if needed
  template:
    src: buildtools.repo.j2
    dest: /etc/yum.repos.d/buildtools.repo
  tags:
    - repo

- name: Adding repo gpg key if needed
  copy: 
    src: files/RPM-GPG-KEY-CentOS-Infra 
    dest: /etc/pki/rpm-gpg/RPM-GPG-KEY-CentOS-Infra
  tags:
    - repo

- name: Install base system packages
  yum:
    name:
      - python36
      - python36-devel
      - python36-rpm-macros
      - rpm-build
      - libselinux-devel
      - libsemanage
      - python3-libsemanage
    state: present
