---
- name: Reload systemd
  systemd:
    daemon_reload: yes

- name: Restart apache
  service:
    name: httpd
    state: restarted
    enabled: true

- name: Reload apache
  service:
    name: httpd
    state: reloaded

- name: Restart fedmsg-hub
  service:
    name: fedmsg-hub
    state: restarted
    enabled: true

- name: Restart mbs poller
  service:
    name: mbs-poller
    state: restarted
    enabled: true

- name: Restart mbs workers
  service:
    name: "mbs-worker@{{ item }}"
    state: restarted
    enabled: true
  with_sequence: start=0 end={{ mbs_num_workers - 1 }}

- name: Restart RabbitMQ
  service:
    name: rabbitmq-server
    state: restarted
    enabled: true
