---
- name: Converge
  hosts: all
  gather_facts: false
  vars:
     mbs_config_messaging: 'in_memory'
  tasks:
    # prepare
    - name: Ensure psql data dir exists
      stat:
        path: /var/lib/pgsql/data/PG_VERSION
      become: true
      register: output
    - name: Install postgresql
      yum:
        name:
          - postgresql-server
          - postgresql-server-devel
          - postgresql
          - python36
          - python36-devel
        state: present
      become: true

    - shell: postgresql-setup --initdb
      become: true
      when: not output.stat.exists

    - name:
      pip:
        name: 
          - psycopg2-binary
        executable: /usr/bin/pip3.6
      become: true

    - copy:
        src: "{{ psql_hba_conf_file }}"
        dest: /var/lib/pgsql/data/pg_hba.conf
      become: true

    - name: Start postgresql
      service:
        name: postgresql
        state: started
        enabled: true
      become: true

    - name: Create a new database with name "acme"
      become: yes
      become_method: sudo
      become_user: postgres
      community.general.postgresql_db:
        name: mbs
        encoding: 'UTF-8'
        lc_collate: 'en_US.UTF-8'
        lc_ctype: 'en_US.UTF-8'
        state: present

    - name: Postgres reset database user
      become: yes
      become_method: sudo
      become_user: postgres
      postgresql_user:
        db: mbs
        name: mbs
        password: mbs
        priv: ALL
        state: present

    - name: Set db owner
      become: yes
      become_method: sudo
      become_user: postgres
      community.general.postgresql_owner:
        db: mbs
        new_owner: mbs

    # run role
    - name: "Include ansible-role-mbs"
      include_role:
        name: "ansible-role-mbs"
      ignore_errors: true
