dependency:
  name: galaxy
driver:
  name: vagrant
  provider:
    name: libvirt
    type: libvirt
platforms:
  - name: instance
    box: centos/8
    memory: 512
    cpus: 1
    instance_raw_config_args:
      - vagrant.plugins = ["vagrant-libvirt"]
    config_options:
      ssh.keep_alive: yes
      ssh.remote_user: "'vagrant'"
      synced_folder: false
    interfaces:
      - network_name: forwarded_port
        guest: 80
        host: 8080
    provision: no
provisioner:
  name: ansible
  inventory:
    group_vars:
      all:
        # msb vars
        mbs_env: stg
        mbs_default_modules_dir: ${MOLECULE_PROJECT_DIRECTORY}/molecule/files/default-modules
        mbs_frontend_https_enabled: false
        mbs_frontend_http_enabled: true
        mbs_config_no_auth: true
        mbs_kojihub_auth_type: 'kerberos'
        mbs_pki_store:  ${MOLECULE_PROJECT_DIRECTORY}/molecule/files/
        # fedmsg vars
        fedmsg_hub_bin: /usr/bin/fedmsg-hub
        fedmsg_env: stg
        fedmsg_log_level: DEBUG
        fedmsg_hub_memory_limit_mb: 300
        fedmsg_hub_auto_restart: false
        fedmsg_enable_websocket_server: false
        fedmsg_websocket_port: 9919
        fedmsg_status_directory: /var/run/fedmsg/status
        fedmsg_post_init_sleep: 1
verifier:
  name: ansible
scenario:
  test_sequence:
    - dependency
    - lint
    - cleanup
    - destroy
    - syntax
    - create
    - prepare
    - converge
    # - idempotence
    - side_effect
    - verify
    - cleanup
    - destroy
